version: '3.8'

services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ruta_express_db
    ports:
      - "5433:5432"  # Cambié a 5433 por si ya tienes otro postgres en 5432
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
